# Generated by Django 4.2.7 on 2024-05-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('report_category', models.CharField(max_length=255, verbose_name='Категория')),
                ('report_text', models.TextField(verbose_name='Описание')),
                ('location_lat', models.FloatField(verbose_name='ФИО')),
                ('location_lon', models.FloatField(verbose_name='ФИО')),
                ('time', models.DateTimeField(verbose_name='Время создания')),
                ('report_photo', models.ImageField(upload_to='report_photos/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Запрос пользователя',
                'verbose_name_plural': 'Запросы пользователей',
            },
        ),
        migrations.CreateModel(
            name='AdminResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('admin_response_text', models.TextField(verbose_name='Описание')),
                ('admin_response_photo', models.ImageField(upload_to='response_photos/', verbose_name='Время создания')),
                ('response_time', models.DateTimeField(auto_now_add=True)),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.userrequest')),
            ],
            options={
                'verbose_name': 'Ответ админа',
                'verbose_name_plural': 'Ответы админов',
            },
        ),
    ]
