# Generated by Django 4.2.7 on 2024-05-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='location_lat',
            field=models.FloatField(verbose_name='латитуд'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='location_lon',
            field=models.FloatField(verbose_name='лонг'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='report_category',
            field=models.CharField(choices=[['Свалка', 'Свалка'], ['Задымление', 'Задымление'], ['Вырубка деревьев', 'Вырубка деревьев'], ['Незаконный выброс естественных отходов', 'Незаконный выброс естественных отходов'], ['Другое', 'Другое']], max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='user_id',
            field=models.IntegerField(verbose_name='Юзер'),
        ),
    ]
