# Generated by Django 4.2.7 on 2024-05-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0002_userrequest_status_alter_userrequest_location_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='age',
        ),
        migrations.AlterField(
            model_name='adminresponse',
            name='admin_response_photo',
            field=models.ImageField(upload_to='response_photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='adminresponse',
            name='response_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='adminresponse',
            name='user_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.userrequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
