# Generated by Django 4.2.7 on 2024-05-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0003_remove_userrequest_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='латитуд'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='location_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='лонг'),
        ),
    ]
